Accepting/Rejecting Match by User
jpsoffice/vmb pull request #54
Opened 2020-09-08 13:30 UTC by bhawanabadlani

2020-09-09 07:39 UTC, rtnpro requested changes
A better way to implement this is to implement `/match/<match_id>/` to show details of the matching profile with "Accept" and "Reject" buttons.

This also will go in line with the future `/matches` endpoint which will list all the matches for the user.

2020-09-09 07:39 UTC, rtnpro commented on vmb/templates/matrimony/emails/matches.html
> +              <tr>
You don't need a `form` here, just a button type link should do the trick. The link/button when clicked should open the link in a new tab.

2020-09-09 07:39 UTC, rtnpro commented on vmb/templates/matrimony/emails/response.html
> +{% extends "matrimony/emails/matches.html" %}
These new templates should not be in `emails`. They are not mailers.

2020-09-09 07:39 UTC, rtnpro commented on vmb/matrimony/models/profiles.py
> +            {"profile": self}
Why expose `profile` here? I don't see usage of `profile` but only `matches` in the template.

2020-09-12 04:52 UTC, rtnpro requested changes

2020-09-12 04:52 UTC, rtnpro commented on vmb/matrimony/urls.py
> +    path("response/<int:id>", views.response, name="response"),
This should be `match/<id>/response`

2020-09-12 04:52 UTC, rtnpro commented on vmb/matrimony/urls.py
> +    path("match/<int:id>", views.match, name="match"),
As a shortcut for now, you can just handle `post` request in this URL to update response. This will avoid using AJAX for now.

2020-09-12 04:52 UTC, rtnpro commented on vmb/matrimony/views.py
> +def response(request, id):
The name does not make sense. If we want to have dedicated views for handling `match` response, we should at least call it `match_response`.

IMO, if we are not implementing AJAX to update match response from the `match_detail` page, it's not worth adding a separate view for response and templates for it.

2020-09-12 04:52 UTC, rtnpro commented on vmb/matrimony/views.py
> +        match = get_object_or_404(Match, male=profile_user, female=profile)
Nice! 👍

2020-09-12 04:52 UTC, rtnpro commented on vmb/matrimony/views.py
> +def match(request, id):
We should be using `Class` based views for views around any model.

2020-09-12 04:52 UTC, rtnpro commented on vmb/templates/matrimony/match/response.html
> +{% extends "matrimony/emails/base.html" %}
Why is it extending from `email` base template? We needn't use `table` in web templates. It's only necessary for email templates.

2020-09-12 04:52 UTC, rtnpro commented on vmb/templates/matrimony/match/match.html
> +
Logically, the match endpoint should show the match details.

2020-11-01 06:28 UTC, jpsofficeonline commented
Closing this PR because of rebase/squash issues.

2020-11-01 06:28 UTC, closed without merging