Minor changes in the form
jpsoffice/vmb pull request #58
Opened 2020-09-30 05:20 UTC by bhawanabadlani

2020-09-30 06:12 UTC, rtnpro requested changes

2020-09-30 06:12 UTC, rtnpro commented on vmb/matrimony/forms.py
> +                _("Brothers married cannot be greater than no. of brothers")
use full word `number` instead of `no.`

2020-09-30 06:13 UTC, rtnpro commented
@bhawanabadlani You commit messages don't make sense: 
![image](https://user-images.githubusercontent.com/231684/94649323-0b5ef800-0312-11eb-9402-e20d62e291de.png)

Each commit message to explicitly mention the changes made, not some vague phrases.

2020-09-30 22:14 UTC, bhawanabadlani commented on vmb/matrimony/forms.py
> +                _("Brothers married cannot be greater than no. of brothers")
ok

2020-10-02 14:33 UTC, rtnpro commented on vmb/matrimony/forms.py
> +        self.fields.required = True
Why do we need this? @bhawanabadlani

2020-10-02 14:52 UTC, rtnpro approved these changes

2020-10-02 14:52 UTC, merged